apiVersion: v1
kind: ConfigMap
metadata:
  name: devices-integration-api-config
  labels:
    app.kubernetes.io/name: devices-integration-api-config
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
data:
  config.properties: |
    # --- Authentication and API Configuration ---
    auth.identity.endpoint=http://identity-service.app-development.svc.cluster.local:9000/oauth2/token
    auth.client.id=analyzer-alinity1-branch-default
    auth.client.secret=${AUTH_CLIENT_SECRET}
    auth.scope=lab.result:read lab.result:write
    core.api.endpoint=http://core-api.app-development.svc.cluster.local:80/bsis
    core.api.results.path=/analyzer-results

    # --- analyzer specific Configuration ---
    server.ip=0.0.0.0
    alinity.analyzer.name=Alinity1
    alinity.receiving.port=5601
    alinity.branch.code=default


    # --- Database Configuration ---
    db.url=jdbc:h2:file:./data/results_buffer;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    db.driver=org.h2.Driver
    db.username=${DB_USERNAME}
    db.password=${DB_PASSWORD}

    # --- RabbitMQ Configuration ---
    rabbitmq.host=rabbitmq
    rabbitmq.port=5672
    rabbitmq.username=${RABBITMQ_USERNAME}
    rabbitmq.password=${RABBITMQ_PASSWORD}
    rabbitmq.exchange.name=analyzer.results.exchange
    rabbitmq.routing.key=analyzer.results

    # --- Local Buffer Configuration ---
    local.buffer.path=./data/lab_results_buffer
    local.buffer.retry.interval.seconds=30
