apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-development

resources:
  - ../../base
  - configmap-devices-integration-api.yaml
  - secretstore-vault.yaml
  - externalsecret-devices-integration-api.yaml

images:
  - name: ghcr.io/habtec/bsis-devices-integrations-api
    newTag: development-latest
