apiVersion: v1
kind: ServiceAccount
metadata:
  name: common-secrets
  labels:
    app.kubernetes.io/name: common-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
