apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-service-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: identity-service-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store-identity-service
  target:
    name: identity-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: bsis/development/shared
        property: DB_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: bsis/development/shared
        property: DB_PASSWORD
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: bsis/development/shared
        property: RABBITMQ_USERNAME
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: bsis/development/shared
        property: RABBITMQ_PASSWORD
    - secretKey: FIREBASE_PROJECT_ID
      remoteRef:
        key: bsis/development/identity-service
        property: FIREBASE_PROJECT_ID
    - secretKey: FIREBASE_CREDENTIALS_JSON
      remoteRef:
        key: bsis/development/identity-service
        property: FIREBASE_CREDENTIALS_JSON
    - secretKey: JWT_SECRET
      remoteRef:
        key: bsis/development/identity-service
        property: JWT_SECRET
    - secretKey: CLIENT_API_SECRET
      remoteRef:
        key: bsis/development/identity-service
        property: CLIENT_API_SECRET
