apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: core-api
  labels:
    app.kubernetes.io/name: core-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: core-api
