apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: identity-service
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: identity-service
