apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
