apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: app-staging
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
