apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  labels:
    app.kubernetes.io/name: ghcr-pull-secret
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store-common-secrets
  target:
    name: ghcr-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
  - secretKey: dockerconfigjson
    remoteRef:
      key: bsis/production/shared
      property: GHCR_DOCKERCONFIGJSON
