apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store-common-secrets
  labels:
    app.kubernetes.io/name: vault-secret-store-common-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: common-secrets-production
          serviceAccountRef:
            name: common-secrets
