apiVersion: v1
kind: ConfigMap
metadata:
  name: facility-client-config
  labels:
    app.kubernetes.io/name: facility-client-config
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
data:
  runtime-config.js: |
    window.__FACILITY_CLIENT_CONFIG__ = {
      apiUrl: "https://core-api-staging.example.com/bsis/",
      identityApiUrl: "https://identity-service-staging.example.com/api",
      oAuthIssuer: "https://identity-service-staging.example.com",
      oAuthClientId: "public-client",
      oAuthScope: "openid profile",
    };
