apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - applicationset-services.yaml
  # - applicationset-rabbitmq.yaml
  - app-vault.yaml
  - app-external-secrets.yaml
  - app-ingress-nginx.yaml
  - app-cert-manager.yaml
  - app-cert-manager-issuers.yaml
  - app-monitoring-base.yaml
  - app-monitoring-stack.yaml
  - app-monitoring-config.yaml
  - app-monitoring-integrations.yaml
