apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-staging

resources:
  - ../../base
  - configmap-identity-service.yaml
  - secretstore-vault.yaml
  - externalsecret-identity-service.yaml

images:
  - name: ghcr.io/habtec/bsis-identity-server
    newTag: staging-latest

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml
  - patch-hpa.yaml
