apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-service
spec:
  tls:
    - hosts:
        - identity-service-staging.example.com
      secretName: identity-service-staging-tls
  rules:
    - host: identity-service-staging.example.com
