apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-service-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: identity-service-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store-identity-service
  target:
    name: identity-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: bsis/staging/identity-service
        property: DB_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: bsis/staging/identity-service
        property: JWT_SECRET
