apiVersion: v1
kind: ServiceAccount
metadata:
  name: facility-client
  labels:
    app.kubernetes.io/name: facility-client
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
