apiVersion: v1
kind: ConfigMap
metadata:
  name: core-api-config
  labels:
    app.kubernetes.io/name: core-api-config
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: bsis
    app.kubernetes.io/managed-by: argocd
data:
  SERVER_PORT: "8080"
  SERVER_SERVLET_CONTEXT_PATH: "/bsis"
  SPRING_PROFILES_ACTIVE: "prod"
  MANAGEMENT_SERVER_PORT: "8081"
  MANAGEMENT_SERVER_ADDRESS: "0.0.0.0"
  OAUTH2_TOKEN_URL: "https://identity-service-development.example.com/oauth2/token"
  OAUTH2_AUTHORIZATION_URL: "https://identity-service-development.example.com/oauth2/authorize"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://identity-service-development.example.com"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_API_CLIENT_TOKEN_URI: "https://identity-service-development.example.com/oauth2/token"
  SPRINGDOC_SWAGGER_UI_OAUTH2_REDIRECT_URL: "https://core-api-development.example.com/bsis/swagger-ui/oauth2-redirect.html"
  SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID: "public-client"
  SPRINGDOC_SWAGGER_UI_OAUTH_USE_PKCE_WITH_AUTHORIZATION_CODE_GRANT: "true"
  SPRINGDOC_SHOW_ACTUATOR: "true"
  APP_UPLOADS_BASE_DIR: "/tmp/uploads"
  APP_IDENTITY_GETDONORBYID: "http://identity-service/api/donors/"
  APP_IDENTITY_GETDONORCSVEXPORT: "http://identity-service/api/donors/export"
  APP_IDENTITY_GETDONORBYDONORNUMBER: "http://identity-service/api/donors/by-numbers/"
  APP_IDENTITY_GETDONORSBYDONORNUMBERS: "http://identity-service/api/donors/by-numbers/"
  APP_IDENTITY_GETCURRENTDONORPROFILE: "http://identity-service/api/donors/me"
  APP_IDENTITY_SEARCHDONORS: "http://identity-service/api/donors/search"
  APP_IDENTITY_GETUSERSBYIDS: "http://identity-service/api/users/by-ids"
  APP_IDENTITY_GETTENANTIDS: "http://identity-service/api/blood-bank/tenants"
  APP_IDENTITY_GETBRANCHESBYTENANTIDS: "http://identity-service/api/blood-bank/search"
  APP_IDENTITY_GETLOCATIONSBYIDS: "http://identity-service/api/global/locations"
  APP_IDENTITY_GETBRANCHES: "http://identity-service/api/blood-bank"
  APP_IDENTITY_GENERATEANALYZERCLIENTSECRET: "http://identity-service/api/analyzers/%s/generate-secret"
  APP_IDENTITY_GETUSERBYUSERNAME: "http://identity-service/api/users/by-username"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
